name: docker compose test
on: push

jobs:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name: start the app
      run: docker-compose up -d
    - name: test
      run: docker run --network container:frontend appropriate/curl -s --retry 10 --retry-connrefused http://localhost:8000/

